sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - LARAVEL_VERSION=5.1.*
  - LARAVEL_VERSION=5.2.*
  - LARAVEL_VERSION=5.3.*
  - LARAVEL_VERSION=5.4.*

before_script:
  - composer self-update
  - composer require "laravel/framework:${LARAVEL_VERSION}"
  - mysql -e 'create database laravel;'

script: phpunit --coverage-clover coverage.xml

after_success:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  exclude:
    - php: 5.5
      env: LARAVEL_VERSION=5.3.*
    - php: 5.5
      env: LARAVEL_VERSION=5.4.*
