sudo: false
language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  - LARAVEL_VERSION=5.6.* PHPUNIT_VERSION=~7.0
  - LARAVEL_VERSION=5.5.* PHPUNIT_VERSION=~6.0
  - LARAVEL_VERSION=5.4.* PHPUNIT_VERSION=~5.7
  - LARAVEL_VERSION=5.3.* PHPUNIT_VERSION=~5.7

before_script:
  - composer self-update
  - composer require "laravel/framework:${LARAVEL_VERSION}" "phpunit/phpunit:${PHPUNIT_VERSION}"
  - mysql -e 'create database laravel;'

script: vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  exclude:
  - php: 5.6
    env: LARAVEL_VERSION=5.5.* PHPUNIT_VERSION=~6.0
  - php: 5.6
    env: LARAVEL_VERSION=5.6.* PHPUNIT_VERSION=~7.0
  - php: 7.0
    env: LARAVEL_VERSION=5.6.* PHPUNIT_VERSION=~7.0
