sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - LARAVEL_VERSION=5.0.*
  - LARAVEL_VERSION=5.1.*

before_script:
  - composer require "laravel/framework:${LARAVEL_VERSION}"
  - mysql -e 'create database laravel;'

script: phpunit --coverage-clover coverage.xml

after_success:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
